os: osx
osx_image: xcode8.3
before_install:
  - brew update
  - brew install cartr/qt4/qt

language: c

jobs:
  include:
    - stage: Build and install OpenSCAP
      script:
        - git clone --depth 1 https://github.com/OpenSCAP/openscap.git
        - pushd openscap
        - ./autogen.sh
        - ./configure
        - make -j 4
        - make install
        - popd
    - stage: Build scap-workbench
      script:
        - ./build-for-osx.sh
