os: osx
osx_image: xcode9.4
before_install:
  - brew update
  - brew install gcc
  - brew install cartr/qt4/qt
  - brew install asciidoctor

language: c

jobs:
  include:
    - stage: Build and install OpenSCAP
      script:
        - git clone --depth 1 https://github.com/redhatrises/openscap.git -b ssize
        - pushd openscap/build
        - cmake -DENABLE_PYTHON3=false -DENABLE_PROBES=false -DENABLE_OSCAP_UTIL_DOCKER=false ../
        - make -j 4
        - make install
        - popd
        - ./build-for-osx.sh
#    - stage: Build scap-workbench
#script:
#- ./build-for-osx.sh
